### ISSUE TITLE
Manual Event Adding

### ISSUE THREAD

**Issue by DadBackFromWalmart** [OneThatWalks/anker-discord-bot#6]
**Is your feature request related to a problem? Please describe.**
Say we have an ancillary event within the office, such as a meeting or holiday office party, or that we go away from the Google Calendar at some point. It would ultimately become necessary for the bot to be able to handle manual event adding.

**Describe the solution you'd like**
Add commands '!add', '!view', '!remove', and '!edit'.

User could add an event in the format of '!add event_name date time @user'.

They could remove an event using '!removed  event_name'. The name must match with an existing event. User can use the below command if they forget the event's name.

They could view personal manual events with '!view', '!view all' to view all manually added events, and '!view @user' to view another user's events. This follows the same structure as the !schedule command, but !schedule should stay reserved for Google Calendar events, and !view would work for manually added events.

They could edit an existing event with '!edit event_name date time @user'. The bot will prompt them for new information for that event, where the user can enter 'new_event_name', 'new_date', 'new_time', and 'new_@user'.

**Describe alternatives you've considered**
Typing out events manually as plain text in the server, and hoping people remember them.... not a great alternative, but it beats carrier pigeons.

**Additional context**
None at this time.

**Comment by OneThatWalks** [comment]
@DadBackFromWalmart 

I like the idea.  It sounds like a good candidate for the !schedule command to be honest.

For example:
`!schedule add start end name`
Would add a named event to your schedule.

`!schedule remove name`
Would remove the named event from your schedule

`!schedule edit start end name`
Would modify an existing named event

We could also add @Mentions to the command to support targeted event adding.  We could then update the `!schedule` command to show named events or not.

What do you think about that?

**Comment by OneThatWalks** [comment]
Moving this to vNext milestone.  I would like to have the MVP (Minimum Viable Product alpha in deployment).  This would be a good candidate for another version release as things stabilize.
