### ISSUE TITLE
!export command

### ISSUE THREAD

**Issue by DadBackFromWalmart** [OneThatWalks/anker-discord-bot#7]
**Is your feature request related to a problem? Please describe.**
Everyone logs in, out, goes for lunch, etc. This is currently typed in Discord, but will eventually be replaced by !login and !logout. However, it'd be nice to have all of this logged in time tracked.

**Describe the solution you'd like**
Add the !export command to take all logged-in time for users and store it in a .csv file, then present said .csv file. I would think the last month of logged-in time would be sufficient to keep stored, but this can be debated. Would be best to show users Logged-In Time in Hours:Minutes:Seconds by day.

**Describe alternatives you've considered**
Current alternative is Matt reading all posts in the #time-clock channel, which is a bit cumbersome. Would like to automate it, which is the sole solution.

**Additional context**
Ask me if any is needed.

**Comment by OneThatWalks** [comment]
@DadBackFromWalmart 
So does that mean if this month is February "last-month" would be Jan 1-31?  Or would it mean the past 30 or so day?  I am wondering what would be most helpful to Matt for this feature.

**Comment by OneThatWalks** [comment]
Also take a look at [this](https://github.com/OneThatWalks/anker-discord-bot/projects/1#card-33413268).  I tried to come up with the feature but would help to have your input and his input of effective implementation.

**Comment by OneThatWalks** [comment]
Based on conversation with Matt we could start with this template

| Day | Time in | Time out | Total |
|-----|---------|----------|-------|
|Bob|              |                |               |
|Jan 1| 8:00AM| 12:00PM|  4 Hours |
|        |  1:00PM| 5:00PM  |  4 Hours|

**Comment by OneThatWalks** [comment]
This has been complete

Use `!help` with the bot to learn more.
